 export const  projectsData = [
    {
        id: 1,
        title: "Next.Js Barber's Website",
        description: "Barber's Website",
        image: "/greenleaf.jpg",
        tag: ["All", "Web"],
        gitUrl: "/",
        previewUrl: "/",
    },
    {
        id: 2,
        title: "Next.Js Electrician Website",
        description: "Electrician Website",
        image: "/greenleaf.jpg",
        tag: ["All", "Web"],
        gitUrl: "/",
        previewUrl: "/",
    },
    {
        id: 3,
        title: "Computer Repair Shop Admin",
        description: "Computer Repair Shop ",
        image: "/greenleaf.jpg",
        tag: ["All", "Web"],
        gitUrl: "/",
        previewUrl: "/",
    },
    {
        id: 4,
        title: "Real Estate Listing Application",
        description: "Real Estate Listing",
        image: "/greenleaf.jpg",
        tag: ["All", "Mobile"],
        gitUrl: "/",
        previewUrl: "/",
    },
    {
        id: 5,
        title: "React Firebase Template",
        description: "Authentication and CRUD operations",
        image: "/greenleaf.jpg",
        tag: ["All", "Web"],
        gitUrl: "/",
        previewUrl: "/",
    },
    {
        id: 6,
        title: "Full-stack Roadmap",
        description: "Project 5 description",
        image: "/greenleaf.jpg",
        tag: ["All", "Web"],
        gitUrl: "/",
        previewUrl: "/",
    },
];